<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-952Q9QQ" failures="3" tests="5" name="chrometest" time="48.146" errors="0" timestamp="2025-09-15T07:43:07 IST">
  <testcase classname="testScript.LoginTest" name="verifyloginwithValidCredentials" time="5.936"/>
  <testcase classname="testScript.LoginTest" name="verifyloginwithValidusernameinvalidpassword" time="0.662"/>
  <testcase classname="testScript.LoginTest" name="verifyloginwithinValidusernamevalidpassword" time="0.437">
    <failure type="java.lang.AssertionError" message="Login is successful with invalid username expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login is successful with invalid username expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at testScript.LoginTest.verifyloginwithinValidusernamevalidpassword(LoginTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginwithinValidusernamevalidpassword -->
  <testcase classname="testScript.LoginTest" name="verifyloginwithinValidCredentials" time="0.301">
    <failure type="java.lang.AssertionError" message="Login is successful with invalid Credential expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login is successful with invalid Credential expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at testScript.LoginTest.verifyloginwithinValidCredentials(LoginTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginwithinValidCredentials -->
  <testcase classname="testScript.LoginTest" name="verifyloginwithinValidCredentials" time="0.535">
    <failure type="java.lang.AssertionError" message="Login is successful with invalid Credential expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login is successful with invalid Credential expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at testScript.LoginTest.verifyloginwithinValidCredentials(LoginTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginwithinValidCredentials -->
</testsuite> <!-- chrometest -->
